### ISSUE TITLE
improve js structure

### ISSUE THREAD

**Issue by karimmtarek** [karimmtarek/timeliner#33]
- move js code from application.js
- create proper js files to move code to and include them in application.js `//= require whatever`
- improve js structure

**Comment by BratCat** [comment]
Where is the code in application.js supposed to be moved to?

**Comment by karimmtarek** [comment]
Good question @BratCat. I think it depends, if the code belongs to the backend of the app, then maybe backend.js and the same goes for the frontend, we can assume that the landing page is part of the backend, in this case.
