### ISSUE TITLE
Add blog feature

### ISSUE THREAD

**Issue by karimmtarek** [karimmtarek/timeliner#4]
- Design index page
- Design show page

**Comment by StrangeTim** [comment]
I will tackle this issue. Do you have any design preferences? (or examples that you particularly like)

**Comment by karimmtarek** [comment]
@StrangeTim you can follow the same theme as [this](http://www.gotimeliner.com/karim-tarek) you can find the psd [there](https://www.behance.net/gallery/28700751/Timeliner-UI-Bundle-Free-PSD).
If you don't like the theme you can design a new theme for the timeline/portfolio and the blog :)
Please let me know if you need any help to get you starting, thanks.

**Comment by StrangeTim** [comment]
What would you think about keeping the time-line theme for listing blog posts, with most recent at top of course, as an index.  The same time-line could be minimized, or compress to, a side bar when an individual blog post is opened.  Either that keep the page static and open the individual post in a modal.

**Comment by karimmtarek** [comment]
Let's go with the first option and see how it's going to turn up, are you planing to do a mockup as a psd first or else?
